<a href="https://colab.research.google.com/github/yashraj-22/ML-Bootcamp-Assignments/blob/main/Programming_Assignment8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

###1. Write a Python Program to Add Two Matrices?

In [8]:
import numpy as np

a = np.array([[1,2,3],[4,5,6],[7,8,9]])
b = np.array([[4,5,6],[7,8,9],[1,2,3]])
c = a + b
print(c)

[[ 5  7  9]
 [11 13 15]
 [ 8 10 12]]


###2. Write a Python Program to Multiply Two Matrices?

In [1]:
import numpy as np

a = np.array([[1,2,3],[4,5,6],[7,8,9]])
b = np.array([[4,5,6],[7,8,9],[1,2,3]])
result = np.array([[0,0,0],[0,0,0],[0,0,0]])
# iterate through rows of a
for i in range(len(a)):
   # iterate through columns of b
   for j in range(len(b[0])):
       # iterate through rows of b
       for k in range(len(b)):
           result[i][j] += a[i][k] * b[k][j]
print(result)

[[ 21  27  33]
 [ 57  72  87]
 [ 93 117 141]]


###3. Write a Python Program to Transpose a Matrix?

In [28]:
import numpy as np

a = np.array([[1,2,3,2],[4,5,6,2],[7,8,9,2]])
result = np.array([[0,0,0],[0,0,0],[0,0,0],[0,0,0]])

for i in range(len(a)):
  for j in range(len(a[0])):
    result[j][i] = a[i][j]

print(result)

[[1 4 7]
 [2 5 8]
 [3 6 9]
 [2 2 2]]


###4. Write a Python Program to Sort Words in Alphabetic Order?

In [33]:
list_of_words = ['d','f','a','z','q','l','c','m','i','g']
n = len(list_of_words)

for i in range(n-1):
  for j in range(i+1, n):
    if ord(list_of_words[i]) > ord(list_of_words[j]):
      list_of_words[i], list_of_words[j] = list_of_words[j], list_of_words[i]

print(list_of_words)

['a', 'c', 'd', 'f', 'g', 'i', 'l', 'm', 'q', 'z']


###5. Write a Python Program to Remove Punctuation From a String?

In [35]:
import string

str_ = "Hello! I'm learning ML from iNeuron."

for i in string.punctuation:
  str_ = str_.replace(i,"")

print(str_)

Hello Im learning ML from iNeuron
